.gitignore, LICENSE-ASL-2.0.txt, README.adoc, README.md, kie-soup-bom/.gitignore, kie-soup-bom/pom.xml, pom.xml
=> Initial scaffolding for kie-soup Maven modules

scripts/release/update-version.sh
needed for the version upgrade of kie-soup in kieAllBuild-master
=> added script for upgrading versions for daily builds

kie-soup-project-datamodel/kie-soup-project-datamodel-commons/src/main/java/org/kie/soup/project/datamodel/commons/oracle/PackageDataModelOracleImpl.java, kie-soup-project-datamodel/kie-soup-project-datamodel-commons/src/test/java/org/kie/soup/project/datamodel/commons/oracle/PackageDataModelOracleImplTest.java
See https://issues.jboss.org/browse/DROOLS-2076
=> DROOLS-2076: [DataModelOracle] DSL Sentences are not loaded

kie-soup-dataset/kie-soup-dataset-elasticsearch/pom.xml, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/main/java/org/dashbuilder/dataprovider/backend/elasticsearch/ElasticSearchDataSetProvider.java, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/main/java/org/dashbuilder/dataprovider/backend/elasticsearch/rest/impl/ElasticSearchNativeClient.java, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/main/java/org/dashbuilder/dataprovider/backend/elasticsearch/rest/impl/ElasticSearchQueryBuilderImpl.java, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/main/java/org/dashbuilder/dataprovider/backend/elasticsearch/rest/impl/NativeClientAggregationsBuilder.java, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/main/java/org/dashbuilder/dataprovider/backend/elasticsearch/rest/impl/NativeClientFactory.java, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/main/java/org/dashbuilder/dataprovider/backend/elasticsearch/rest/impl/NativeClientQueryBuilder.java, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/main/java/org/dashbuilder/dataprovider/backend/elasticsearch/rest/impl/NativeClientResponseParser.java, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/main/java/org/dashbuilder/dataprovider/backend/elasticsearch/rest/model/FieldMappingResponse.java, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/main/java/org/dashbuilder/dataprovider/backend/elasticsearch/rest/util/ElasticSearchUtils.java, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/test/java/org/dashbuilder/dataprovider/backend/elasticsearch/ElasticSearchDataSetTest.java, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/test/java/org/dashbuilder/dataprovider/backend/elasticsearch/suite/ElasticSearchTestSuite.java, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/test/resources/elasticsearch.yml, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/test/resources/org/dashbuilder/dataprovider/backend/elasticsearch/server/example-data/emptyIntervals-mappings.json, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/test/resources/org/dashbuilder/dataprovider/backend/elasticsearch/server/example-data/expensereports-csensitive-mappings.json, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/test/resources/org/dashbuilder/dataprovider/backend/elasticsearch/server/example-data/expensereports-mappings.json, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/test/resources/org/dashbuilder/dataprovider/backend/elasticsearch/server/example-data/multifields-mappings.json, pom.xml
@dgutierr @romartin I had to put this PR with the others that involve changing ES and Lucene version
I think this PR is old now with this project move, should we close it?
https://github.com/dashbuilder/dashbuilder/pull/390
=> [AF-549-elastic]: Upgraded Elasticserch version to 5.6.1.

kie-soup-project-datamodel/kie-soup-project-datamodel-api/src/main/java/org/kie/soup/project/datamodel/imports/Import.java
Ensemble with:
- kiegroup/kie-wb-common#1306
- kiegroup/drools-wb#720
=> DROOLS-1798: Add constructor of an Import class

kie-soup-commons/src/main/java/org/kie/soup/commons/util/ListSplitter.java, kie-soup-commons/src/main/resources/org/kie/soup/commons/KIESoupCommons.gwt.xml, kie-soup-commons/src/test/java/org/kie/soup/commons/util/ListSplitterTest.java
https://issues.jboss.org/browse/DROOLS-2263
Bundle:
https://github.com/kiegroup/kie-soup/pull/29
https://github.com/kiegroup/drools/pull/1727
https://github.com/kiegroup/drools-wb/pull/777
=> DROOLS-2263 : Unexpected results in GDST when using enumerations with commas

kie-soup-commons/src/main/java/org/kie/soup/commons/util/ListSplitter.java, kie-soup-commons/src/main/resources/org/kie/soup/commons/KIESoupCommons.gwt.xml, kie-soup-commons/src/test/java/org/kie/soup/commons/util/ListSplitterTest.java
(cherry picked from commit 88872ad0f405dd11cef76c1c1a6a2e98b1affb4b)
https://issues.jboss.org/browse/DROOLS-2263
Bundle:
https://github.com/kiegroup/kie-soup/pull/30
https://github.com/kiegroup/drools/pull/1728
https://github.com/kiegroup/drools-wb/pull/778
=> [7.5.x] DROOLS-2263 : Unexpected results in GDST when using enumerations with commas

kie-soup-commons/src/main/java/org/kie/soup/commons/util/ListSplitter.java, kie-soup-commons/src/test/java/org/kie/soup/commons/util/ListSplitterTest.java
Dependent on #29 
@manstis @Rikkola please have a look.
=> DROOLS-2263: Cover case when not all enums use quote character

kie-soup-bom/pom.xml, pom.xml
https://issues.jboss.org/browse/RHDM-251
=> [DO NOT MERGE yet] RHDM-251 Upgrading to Wildfly 11

kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/DataSetLookupConstraints.java, kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/json/DataSetDefJSONMarshaller.java, kie-soup-dataset/kie-soup-dataset-api/src/test/java/org/dashbuilder/dataset/json/DataSetLookupJsonTest.java, kie-soup-dataset/kie-soup-dataset-core/src/test/java/org/dashbuilder/comparator/ComparatorUtilsTest.java, kie-soup-dataset/kie-soup-dataset-core/src/test/java/org/dashbuilder/dataprovider/BeanDataSetGeneratorTest.java, kie-soup-dataset/kie-soup-dataset-core/src/test/java/org/dashbuilder/dataset/DataSetIndexTest.java, kie-soup-dataset/kie-soup-dataset-core/src/test/java/org/dashbuilder/dataset/DataSetNestedGroupTest.java, kie-soup-dataset/kie-soup-dataset-core/src/test/java/org/dashbuilder/dataset/DataSetSortTest.java, kie-soup-dataset/kie-soup-dataset-csv/src/test/java/org/dashbuilder/dataprovider/backend/csv/CSVDataSetBasicTest.java, kie-soup-dataset/kie-soup-dataset-csv/src/test/java/org/dashbuilder/dataprovider/backend/csv/CSVDataSetDefJSONTest.java, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/test/java/org/dashbuilder/dataprovider/backend/elasticsearch/ElasticSearchDataSetCustomColumnsTest.java, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/test/java/org/dashbuilder/dataprovider/backend/elasticsearch/ElasticSearchDataSetTest.java, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/test/java/org/dashbuilder/dataprovider/backend/elasticsearch/ElasticSearchDataSetTestBase.java, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/test/java/org/dashbuilder/dataprovider/backend/elasticsearch/ElasticSearchEmptyIntervalsTest.java, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/test/java/org/dashbuilder/dataprovider/backend/elasticsearch/ElasticSearchMultiFieldsTest.java, kie-soup-dataset/kie-soup-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/SQLDataSetCacheTest.java, kie-soup-dataset/kie-soup-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/SQLDataSetDefTest.java, kie-soup-dataset/kie-soup-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/SQLDataSetTestBase.java, kie-soup-dataset/kie-soup-json/src/main/java/org/dashbuilder/json/JsonTokenizer.java
@dgutierr  please check. My console is all yellow, when compiling this project. Fix some compiler / deprecation warnings.
=> Fix some deprecation warnings

kie-soup-dataset/kie-soup-dataset-core/pom.xml, kie-soup-dataset/kie-soup-dataset-core/src/test/java/org/dashbuilder/comparator/ComparatorUtilsTest.java, kie-soup-dataset/kie-soup-dataset-core/src/test/java/org/dashbuilder/dataset/AggregateFunctionTest.java, kie-soup-dataset/kie-soup-dataset-core/src/test/java/org/dashbuilder/dataset/ChronometerTest.java, kie-soup-dataset/kie-soup-dataset-core/src/test/java/org/dashbuilder/dataset/DataSetFilterTest.java, kie-soup-dataset/kie-soup-dataset-core/src/test/java/org/dashbuilder/dataset/DataSetGroupTest.java, kie-soup-dataset/kie-soup-dataset-core/src/test/java/org/dashbuilder/dataset/DataSetIndexTest.java, kie-soup-dataset/kie-soup-dataset-core/src/test/java/org/dashbuilder/dataset/DataSetLookupConstraintsTest.java, kie-soup-dataset/kie-soup-dataset-core/src/test/java/org/dashbuilder/dataset/DataSetNestedGroupTest.java, kie-soup-dataset/kie-soup-dataset-core/src/test/java/org/dashbuilder/dataset/DataSetTrimTest.java, kie-soup-dataset/kie-soup-dataset-core/src/test/java/org/dashbuilder/dataset/date/DateUtilsTest.java, kie-soup-dataset/kie-soup-dataset-core/src/test/java/org/dashbuilder/dataset/uuid/UUIDGeneratorTest.java, kie-soup-dataset/kie-soup-dataset-csv/pom.xml, kie-soup-dataset/kie-soup-dataset-csv/src/test/java/org/dashbuilder/dataprovider/backend/csv/CSVDataSetBasicTest.java, kie-soup-dataset/kie-soup-dataset-csv/src/test/java/org/dashbuilder/dataprovider/backend/csv/CSVDataSetDefJSONTest.java, kie-soup-dataset/kie-soup-dataset-elasticsearch/pom.xml, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/test/java/org/dashbuilder/dataprovider/backend/elasticsearch/ElasticSearchDataSetTest.java, kie-soup-dataset/kie-soup-dataset-sql/pom.xml, kie-soup-dataset/kie-soup-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/SQLDataSetCacheTest.java, kie-soup-dataset/kie-soup-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/SQLDataSetDefTest.java, kie-soup-dataset/kie-soup-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/SQLTableDataSetLookupTest.java
fest-assert is project is no longer supported anymore and has been superseded by AssertJ. Replace all usage of `fest-assert-core` by `assertj-core`
=> Use AssertJ instead of Fest

pom.xml
cherry picked commit for RHDM-251
=> RHDM-24: updated jackson version to be the same as in kie-parent (#25)

kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/def/BeanDataSetDef.java, kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/def/CSVDataSetDef.java, kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/def/DataSetDef.java, kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/def/ElasticSearchDataSetDef.java, kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/def/SQLDataSetDef.java, kie-soup-dataset/kie-soup-dataset-api/src/test/java/org/dashbuilder/dataset/DataSetDefTest.java
Changes required by https://github.com/kiegroup/appformer/pull/229
=> AF-1048: "Data Sets" screen allows discarding data without warning

kie-soup-dataset/kie-soup-dataset-elasticsearch/src/test/java/org/dashbuilder/dataprovider/backend/elasticsearch/suite/ElasticSearchTestSuite.java
@dgutierr Would you mind to review it please?
=> [AF-1111] Added more time to compile elasticsearch scripts

kie-soup-dataset/kie-soup-dataset-elasticsearch/src/test/java/org/dashbuilder/dataprovider/backend/elasticsearch/suite/ElasticSearchTestSuite.java, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/test/resources/elasticsearch.yml
@mbiarnes @mareknovotny Would you mind to review?
=> [AF-1145]: Container removed if exist before test

kie-soup-commons/src/main/java/org/kie/soup/commons/util/ListSplitter.java, kie-soup-commons/src/test/java/org/kie/soup/commons/util/ListSplitterTest.java
https://issues.jboss.org/browse/DROOLS-2629
@manstis @jomarko If you could please review.
https://github.com/kiegroup/kie-soup/pull/47
https://github.com/kiegroup/kie-wb-common/pull/1890
=> DROOLS-2629 : Complex enumerations are not selected in BRL multi value constraint

kie-soup-commons/src/test/java/org/kie/soup/commons/util/ListSplitterTest.java
Dependent on #47 
@Rikkola please have a look
=> DROOLS-2629: Increase coverage of complex enumerations splitter

kie-soup-commons/src/main/java/org/kie/soup/commons/util/ListSplitter.java, kie-soup-commons/src/main/java/org/kie/soup/commons/util/Lists.java, kie-soup-commons/src/main/java/org/kie/soup/commons/util/Maps.java, kie-soup-commons/src/main/java/org/kie/soup/commons/util/Sets.java, kie-soup-commons/src/test/java/org/kie/soup/commons/util/ListSplitterTest.java, kie-soup-commons/src/test/java/org/kie/soup/commons/util/ListsTest.java, kie-soup-commons/src/test/java/org/kie/soup/commons/util/MapsTest.java, kie-soup-commons/src/test/java/org/kie/soup/commons/util/SetsTest.java, kie-soup-dataset/kie-soup-dataset-elasticsearch/pom.xml, kie-soup-dataset/kie-soup-dataset-elasticsearch/src/main/java/org/dashbuilder/dataprovider/backend/elasticsearch/rest/impl/NativeClientAggregationsBuilder.java
Hi @manstis, @wmedvede, @evacchi, @LuboTerifaj,
It is a basic Builders moved to general repo and small example how it will work.
P.S. also it contains some minor refactoring of nearest files. If you wish I can revert it, or we can merge this PR without squashing.
=> Basic builders

kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/embedder/MavenProjectLoader.java
Workbench offline 7.11.x
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/829
https://github.com/kiegroup/kie-soup/pull/57
https://github.com/kiegroup/appformer/pull/459
https://github.com/kiegroup/kie-wb-common/pull/2117
https://github.com/kiegroup/kie-wb-distributions/pull/811
@porcelli @domhanak @jhrcek
=> [AF-1528] 7.11.x Workbench offline 

kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/embedder/MavenProjectLoader.java
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/826
https://github.com/kiegroup/kie-wb-distributions/pull/806
https://github.com/kiegroup/kie-wb-common/pull/2103
https://github.com/kiegroup/appformer/pull/450
@porcelli @domhanak @jhrcek
=> [AF-1528] Workbench offline

kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/embedder/MavenProjectLoader.java
FIxing some issues on offline behavior, the PRs that compose the changes are:
https://github.com/kiegroup/kie-soup/pull/59
https://github.com/kiegroup/appformer/pull/462
https://github.com/kiegroup/kie-wb-common/pull/2127
https://github.com/kiegroup/kie-wb-distributions/pull/814
=> AF-1528: improvements and consitency on web tooling behavior if offline

kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/embedder/MavenProjectLoader.java
These PRs should be merged all together:
https://github.com/kiegroup/kie-soup/pull/65
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/839
https://github.com/kiegroup/appformer/pull/470
https://github.com/kiegroup/kie-wb-common/pull/2135
https://github.com/kiegroup/kie-wb-distributions/pull/818
https://github.com/kiegroup/kie-docs/pull/1094
=> AF-1528 revert

pom.xml
Signed-off-by: Piotr Szubiakowski <pszubiak@redhat.com>
=> RHDM-373 jackson-databind version update from 2.8.9 to 2.8.10 - 7.11.x

pom.xml
Signed-off-by: Piotr Szubiakowski <pszubiak@redhat.com>
=> RHDM-373 jackson-databind version update from 2.8.9 to 2.8.10.

kie-soup-project-datamodel/kie-soup-project-datamodel-api/src/main/java/org/kie/soup/project/datamodel/imports/Import.java
configuration, inline edit.
@cristianonicolai  Please review it.
=> JBPM-7504 Not possible to edit existing Deployment Descriptor

kie-soup-maven-utils/kie-soup-maven-integration/pom.xml, kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/Aether.java, kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/embedder/MavenEmbedder.java, kie-soup-maven-utils/kie-soup-maven-integration/src/test/java/org/appformer/maven/integration/AetherTest.java, kie-soup-maven-utils/kie-soup-maven-integration/src/test/java/org/appformer/maven/integration/embedder/MavenEmbedderTest.java
There's also an improvement related to forced offline to not add maven central, what makes total sense.
=> AF-1646: if not offline, and a artifact has a bad description, we delete it and try resolve again.

kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/DataSetLookup.java, kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/def/DataSetDefRegistry.java, kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/def/DataSetPostProcessor.java, kie-soup-dataset/kie-soup-dataset-core/src/main/java/org/dashbuilder/dataset/DataSetDefRegistryImpl.java, kie-soup-dataset/kie-soup-dataset-core/src/main/java/org/dashbuilder/dataset/DataSetManagerImpl.java, kie-soup-dataset/kie-soup-dataset-core/src/test/java/org/dashbuilder/dataset/DataSetDefRegistryTest.java
Assembly:
- https://github.com/kiegroup/droolsjbpm-integration/pull/1799
- https://github.com/kiegroup/jbpm/pull/1473
- https://github.com/kiegroup/kie-soup/pull/84
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/379
=> JBPM-8347 - Added DataSetPostProcessor

kie-soup-commons/src/main/java/org/kie/soup/commons/cron/CronExpression.java, kie-soup-commons/src/main/resources/org/kie/soup/commons/KIESoupCommons.gwt.xml, kie-soup-commons/src/test/java/org/kie/soup/commons/cron/CronExpressionTest.java
- Splits the CronExpression in drools into a GWT compatible part required by Stunner and the non GWT complatible methods remains in drools
=> JBPM-8445: Stunner -  unable to set cycle timer with cron expression

kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/MavenRepositoryConfiguration.java, kie-soup-maven-utils/kie-soup-maven-integration/src/test/java/org/appformer/maven/integration/MavenRepositoryTest.java, kie-soup-maven-utils/kie-soup-maven-integration/src/test/resources/org/appformer/maven/integration/settings_custom.xml
(cherry picked from commit 39f554142db5ceb8e854dea2c3eb4e5a06d1afeb)
Please merge only when branch 7.23.x is unlocked.
=> DROOLS-4151 Fill proxy from settings.xml for each remote Maven repository

kie-soup-maven-utils/kie-soup-maven-integration/src/test/java/org/appformer/maven/integration/MavenRepositoryTest.java
(cherry picked from commit 46a80638f3fbc80dc2b54c0b0670c358c1701a3c)
@mareknovotny @jiripetrlik I am not sure if it is possible to cherrypick things to 7.23.x now, however this is just a test fix.
=> DROOLS-4264 Check just the test repositories in proxy test (#97)

kie-soup-dataset/kie-soup-dataset-elasticsearch/src/main/java/org/dashbuilder/dataprovider/backend/elasticsearch/rest/impl/NativeClientAggregationsBuilder.java, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/JDBCUtils.java, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/dialect/DefaultDialect.java, kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/MavenRepository.java, kie-soup-maven-utils/kie-soup-maven-support/src/main/java/org/appformer/maven/support/MinimalPomParser.java
@jesuino @ederign Please take a look :) 
It should get rid of 3 out of 5 blockers from  - https://sonarcloud.io/project/issues?id=kiegroup_kie-soup&resolved=false&types=BUG  and some major issues.
2 remaining blockers are marked as won't fix.
=> AF-2145: Fix kie-soup issues from sonar analysis

kie-soup-dataset/kie-soup-dataset-sql-tests/pom.xml, kie-soup-dataset/kie-soup-dataset-sql/pom.xml, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/JDBCUtils.java, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/ResultSetConsumer.java, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/ResultSetHandler.java, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/SQLDataSetProvider.java, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/dialect/SQLServerDialect.java, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/model/Select.java, kie-soup-dataset/kie-soup-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/JDBCUtilsTest.java, kie-soup-dataset/kie-soup-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/SQLCloseResourcesTest.java
Bringing back fixes for unclosed statements and result sets
=> AF-2245: Dashbuilder not closing ResultSets and Statements

kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/Aether.java, kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/embedder/MavenProjectLoader.java, kie-soup-maven-utils/kie-soup-maven-integration/src/test/java/org/appformer/maven/integration/embedder/MavenProjectLoaderTest.java
Merge with https://github.com/kiegroup/kie-soup/pull/116
=> AF-2276: Fixing is offline setting access

kie-soup-dataset/kie-soup-dataset-sql-tests/pom.xml, kie-soup-dataset/kie-soup-dataset-sql/pom.xml, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/JDBCUtils.java, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/ResultSetConsumer.java, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/ResultSetHandler.java, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/SQLDataSetProvider.java, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/dialect/SQLServerDialect.java, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/model/Select.java, kie-soup-dataset/kie-soup-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/JDBCUtilsTest.java, kie-soup-dataset/kie-soup-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/SQLCloseResourcesTest.java
* AF-2245: Dashbuilder not closing ResultSets and Statements
* AF-2245: Making ResultSetHandler AutoCloseable
=> [7.26.x] AF-2245: Dashbuilder not closing ResultSets and Statements (#113)

kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/Aether.java, kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/embedder/MavenProjectLoader.java, kie-soup-maven-utils/kie-soup-maven-integration/src/test/java/org/appformer/maven/integration/embedder/MavenProjectLoaderTest.java
backport of #116
merge with https://github.com/kiegroup/kie-wb-common/pull/2997
=> AF-2276: Fixing is offline setting access (#116)

kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/Aether.java
Guys, with this fix the kiegroup/droolsjbpm-integration#1864 passes locally.
=> DROOLS-4944 - Change Maven Central to HTTPS in Aether

kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/embedder/MavenEmbedder.java
**Task**: [AF-2366](https://issues.redhat.com/browse/AF-2366)
**Related PRs**:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1151
- https://github.com/kiegroup/kie-soup/pull/124
- https://github.com/kiegroup/appformer/pull/872
- https://github.com/kiegroup/kie-wb-common/pull/3098
- https://github.com/kiegroup/jbpm-wb/pull/1406
- https://github.com/kiegroup/drools-wb/pull/1278
- https://github.com/kiegroup/optaplanner-wb/pull/352
- https://github.com/kiegroup/kie-wb-distributions/pull/1005
=> [AF-2366] BC Maven Archetype Support

Jenkinsfile, Jenkinsfile.downstream, Jenkinsfile.downstream.production
BXMSPROD-592
depends on:
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/5
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1160
=> BXMSPROD-592 upstream and downstream jenkins configuration

kie-soup-maven-utils/kie-soup-maven-integration/pom.xml
https://issues.redhat.com/browse/RHDM-1283
Exclude transitive plexus-utils versions, see RHDM-1283[1] for more information.
[1] https://issues.redhat.com/browse/RHDM-1283?focusedCommentId=14048828&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14048828
=> RHDM-1283 Exclude transitive plexus-utils versions.

kie-soup-xstream/src/main/java/org/kie/soup/xstream/XStreamUtils.java
=> DROOLS-5431 DMN XStream and JDK11

kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/ArtifactResolver.java, kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/DefaultArtifactResolver.java, kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/InJarArtifactResolver.java
Jira
https://issues.redhat.com/browse/JBPM-9178
=> [JBPM-9178] Immutable SpringBoot Deployment

pom.xml
https://issues.redhat.com/browse/RHDM-1338
Related to:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1461
- https://github.com/kiegroup/kie-soup/pull/156
- https://github.com/kiegroup/appformer/pull/1049
=> RHDM-1338 org.apache.logging.log4j:log4j-api and log4j-core 2.13.2

.github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-1025
* https://github.com/kiegroup/lienzo-core/pull/135
* https://github.com/kiegroup/lienzo-tests/pull/110
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1489
* https://github.com/kiegroup/kie-soup/pull/160
* https://github.com/kiegroup/appformer/pull/1063
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/478
* https://github.com/kiegroup/drools/pull/3177
* https://github.com/kiegroup/optaplanner/pull/978
* https://github.com/kiegroup/jbpm/pull/1783
* https://github.com/kiegroup/kie-jpmml-integration/pull/45
* https://github.com/kiegroup/droolsjbpm-integration/pull/2290
* https://github.com/kiegroup/openshift-drools-hacep/pull/101
* https://github.com/kiegroup/droolsjbpm-tools/pull/121
* …
=> BXMSPROD-1025 pull request configuration centralized

kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/dialect/DB2Dialect.java, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/dialect/DefaultDialect.java, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/dialect/OracleDialect.java, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/dialect/OracleLegacyDialect.java, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/dialect/SQLServerDialect.java, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/dialect/SybaseASEDialect.java
Changing db dialects to ensure query is generated with limit 0
=> [JBPM-9099] Long running query at kie-server startup

kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/dialect/SQLServerDialect.java
Rolling back a couple of if statements that caused the endless loop for SQLServer
=> [RPHAM-3353] JBPM-9099 has introduced a bug dealing with SQLServer

kie-soup-dataset/kie-soup-dataset-api/src/test/java/org/dashbuilder/dataset/DataSetApiLookupConstraintsTest.java, kie-soup-dataset/kie-soup-dataset-sql-tests/pom.xml, kie-soup-dataset/kie-soup-dataset-sql/pom.xml, kie-soup-dataset/kie-soup-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/SQLCloseResourcesTest.java, pom.xml
**Upgrade JDK 11 + GWT 2.9**
Feel free to comment and/or raise any concerns.
This PR continues the work done in 
- https://github.com/kiegroup/appformer/pull/1030
- https://github.com/kiegroup/appformer/pull/1039
Thanks guys for that!
**JIRA**:
[AF-1799](https://issues.redhat.com/browse/AF-1799)
**Parent Pull Request**:
- https://github.com/kiegroup/lienzo-core/pull/134
<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>
* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>
* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* <b>an upstream …
=> AF-1799: Upgrade JDK 11 + GWT 2.9

kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataprovider/DataSetProviderType.java, kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataprovider/PrometheusProviderType.java, kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/def/DataSetDefFactory.java, kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/def/PrometheusDataSetDef.java, kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/def/PrometheusDataSetDefBuilder.java, kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/impl/PrometheusDataSetDefBuilderImpl.java, kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/json/PrometheusDefJSONMarshaller.java, kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/validation/groups/PrometheusDataSetDefValidation.java, kie-soup-dataset/kie-soup-dataset-api/src/main/resources/META-INF/ErraiApp.properties, kie-soup-dataset/kie-soup-dataset-prometheus/pom.xml, kie-soup-dataset/kie-soup-dataset-prometheus/src/main/java/org/dashbuilder/dataprovider/prometheus/PrometheusDataSetProvider.java, kie-soup-dataset/kie-soup-dataset-prometheus/src/main/java/org/dashbuilder/dataprovider/prometheus/client/HttpClient.java, kie-soup-dataset/kie-soup-dataset-prometheus/src/main/java/org/dashbuilder/dataprovider/prometheus/client/MetricHelper.java, kie-soup-dataset/kie-soup-dataset-prometheus/src/main/java/org/dashbuilder/dataprovider/prometheus/client/PrometheusClient.java, kie-soup-dataset/kie-soup-dataset-prometheus/src/main/java/org/dashbuilder/dataprovider/prometheus/client/PrometheusCredentialProvider.java, kie-soup-dataset/kie-soup-dataset-prometheus/src/main/java/org/dashbuilder/dataprovider/prometheus/client/QueryResponse.java, kie-soup-dataset/kie-soup-dataset-prometheus/src/main/java/org/dashbuilder/dataprovider/prometheus/client/QueryResponseBuilder.java, kie-soup-dataset/kie-soup-dataset-prometheus/src/main/java/org/dashbuilder/dataprovider/prometheus/client/QueryResponseParser.java, kie-soup-dataset/kie-soup-dataset-prometheus/src/main/java/org/dashbuilder/dataprovider/prometheus/client/Result.java, kie-soup-dataset/kie-soup-dataset-prometheus/src/main/java/org/dashbuilder/dataprovider/prometheus/client/ResultType.java, kie-soup-dataset/kie-soup-dataset-prometheus/src/main/java/org/dashbuilder/dataprovider/prometheus/client/Status.java, kie-soup-dataset/kie-soup-dataset-prometheus/src/main/java/org/dashbuilder/dataprovider/prometheus/client/Value.java, kie-soup-dataset/kie-soup-dataset-prometheus/src/test/java/org/dashbuilder/dataprovider/prometheus/PrometheusDataSetProviderTest.java, kie-soup-dataset/kie-soup-dataset-prometheus/src/test/java/org/dashbuilder/dataprovider/prometheus/client/PrometheusClientTest.java, kie-soup-dataset/kie-soup-dataset-prometheus/src/test/java/org/dashbuilder/dataprovider/prometheus/client/QueryResponseParserTest.java, kie-soup-dataset/pom.xml
The dataset provider impl for Prometheus.
Part of an ensemble. Merge with:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1566
https://github.com/kiegroup/appformer/pull/1091
=> AF-2766: Dashbuilder Prometheus data-set provider

kie-soup-dataset/kie-soup-dataset-prometheus/src/test/java/org/dashbuilder/dataprovider/prometheus/client/PrometheusClientTest.java
For more details see:
- https://issues.redhat.com/browse/AF-2804
=> AF-2804: Remove stubbing that is not needed

kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/dialect/SybaseASEDialect.java, kie-soup-dataset/kie-soup-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/SQLDataSetMetadataLimitTest.java
JIRA: [JBPM-9624](https://issues.redhat.com/browse/JBPM-9624)
=> [JBPM-9626] Create test for checking limit 0 at getColumns

kie-soup-project-datamodel/kie-soup-project-datamodel-api/src/main/java/org/kie/soup/project/datamodel/oracle/DataType.java, kie-soup-project-datamodel/kie-soup-project-datamodel-api/src/test/java/org/kie/soup/project/datamodel/oracle/DataTypeTest.java
**JIRA**: [DROOLS-6033](https://issues.redhat.com/browse/DROOLS-6033)
**Referenced Pull Requests**:
* https://github.com/kiegroup/kie-soup/pull/178
* https://github.com/kiegroup/kie-wb-common/pull/3566
=> DROOLS-6033 : LocaldateTime guided rule presents it incorrectly.

kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/DataSetLookupBuilder.java, kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/group/ColumnGroup.java, kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/impl/AbstractDataSetLookupBuilder.java, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/SQLDataSetProvider.java, kie-soup-dataset/kie-soup-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/SQLDataSetTrimTest.java
Adding post  flag to be able to disable in memory operations after query
=> [JBPM-9619] Task inbox fails to display data due to inefficient query

kie-soup-dataset/kie-soup-dataset-kafka/src/main/java/org/dashbuilder/dataprovider/kafka/mbean/JMXRMIConnectorProvider.java, kie-soup-dataset/kie-soup-dataset-kafka/src/main/java/org/dashbuilder/dataprovider/kafka/mbean/MBeanServerConnectionProvider.java
Related to: https://github.com/kiegroup/kie-soup/pull/188
Cherry Pick: 
* https://github.com/kiegroup/kie-soup/pull/189
* https://github.com/kiegroup/appformer/pull/1125
* https://github.com/kiegroup/kie-wb-distributions/pull/1094
=> JBPM-9678: Standalone workbench does not start

kie-soup-project-datamodel/kie-soup-project-datamodel-api/src/main/java/org/kie/soup/project/datamodel/oracle/OperatorsOracle.java, kie-soup-project-datamodel/kie-soup-project-datamodel-api/src/test/java/org/kie/soup/project/datamodel/OperatorsOracleTest.java
(cherry picked from commit 4fbacf9bfc58d03ea82ed0228a8acd55d44f0f8d)
**JIRA**: 
[DROOLS-6268](https://issues.redhat.com/browse/DROOLS-6268)
**referenced Pull Requests**:
* https://github.com/kiegroup/kie-soup/pull/194
* https://github.com/kiegroup/drools/pull/3689
* https://github.com/kiegroup/kie-wb-common/pull/3620
* https://github.com/kiegroup/drools-wb/pull/1483
=> [7.52.x] DROOLS-6268 : Guided Rule Editor: Add memberOf and not memberOf operators

kie-soup-project-datamodel/kie-soup-project-datamodel-api/src/main/java/org/kie/soup/project/datamodel/oracle/OperatorsOracle.java, kie-soup-project-datamodel/kie-soup-project-datamodel-api/src/test/java/org/kie/soup/project/datamodel/OperatorsOracleTest.java
**JIRA**:  
[DROOLS-6268](https://issues.redhat.com/browse/DROOLS-6268)
**referenced Pull Requests**: 
* https://github.com/kiegroup/kie-soup/pull/193
* https://github.com/kiegroup/drools/pull/3524
* https://github.com/kiegroup/kie-wb-common/pull/3619
* https://github.com/kiegroup/drools-wb/pull/1481
=> DROOLS-6268 : Fix for GRE in

kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/dialect/OracleDialect.java
JIRA: [JBPM-9811](https://issues.redhat.com/browse/JBPM-9811)
=> [JBPM-9811] Oracle - Long running query at kie-server startup

kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/json/DataSetDefJSONMarshaller.java, kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/json/DataSetJSONMarshaller.java, kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/json/DataSetMetadataJSONMarshaller.java, kie-soup-dataset/kie-soup-dataset-api/src/test/java/org/dashbuilder/dataset/json/DataSetDefJsonTest.java, kie-soup-dataset/kie-soup-dataset-api/src/test/java/org/dashbuilder/dataset/json/DataSetJsonTest.java, kie-soup-dataset/kie-soup-dataset-api/src/test/java/org/dashbuilder/dataset/json/DataSetMetadataJSONMarshallerTest.java, kie-soup-dataset/kie-soup-dataset-csv/src/main/java/org/dashbuilder/dataprovider/csv/CSVDataSetProvider.java, kie-soup-dataset/kie-soup-dataset-csv/src/main/java/org/dashbuilder/dataprovider/csv/CSVParser.java, kie-soup-dataset/kie-soup-dataset-prometheus/src/main/java/org/dashbuilder/dataprovider/prometheus/client/HttpClient.java
JIRA:
https://issues.redhat.com/browse/AF-2852
Merge with: https://github.com/kiegroup/appformer/pull/1152
I had to add marshaller and fix issues in existing marshaller because DashBuilder runtime needs to exchange JSON instead using Errai RPC
Also had to fix Dataset marshaller to make it possible to use datasets as Json from DB Runtime
=> AF-2852: Marshaller for DataSetMetadata

kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/InJarArtifactResolver.java
depends on 
https://github.com/kiegroup/droolsjbpm-integration/pull/2554
=> [JBPM-9829] Spring Boot jar containing kjar and commons-beanutils causes "Could not read pom in jar" error

README.adoc, pom.xml
* Changed restrictive terms
**JIRA**: 
[AF-2830](https://issues.redhat.com/browse/AF-2830)
[AF-2829](https://issues.redhat.com/browse/AF-2829)
**referenced Pull Requests**: 
* https://github.com/kiegroup/optaplanner-wb/pull/401
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1708
* https://github.com/kiegroup/kie-wb-playground/pull/117
* https://github.com/kiegroup/appformer/pull/1178
* https://github.com/kiegroup/kie-wb-common/pull/3665
* https://github.com/kiegroup/drools-wb/pull/1509
* https://github.com/kiegroup/jbpm-designer/pull/914
* https://github.com/kiegroup/jbpm-wb/pull/1509
* https://github.com/kiegroup/kie-wb-distributions/pull/1118
<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>
* <b>a pull request</b> please add comment: …
=> [DO NOT MERGE] AF-2830 : Conscious language initiative on KIE-SOUP

kie-soup-dataset/kie-soup-dataset-sql-tests/pom.xml
Signed-off-by: Alberto Morales Perez <almorale@redhat.com>
**JIRA**: [RHPAM-3897](https://issues.redhat.com/browse/RHPAM-3897)
**referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1768
* https://github.com/kiegroup/jbpm/pull/2016
* https://github.com/kiegroup/drools/pull/3832
* https://github.com/kiegroup/droolsjbpm-integration/pull/2602
* https://github.com/kiegroup/jbpm-work-items/pull/215
* https://github.com/kiegroup/kie-jpmml-integration/pull/64
* https://github.com/kiegroup/optaplanner/pull/1574
* https://github.com/jboss-integration/rhba-installers/pull/92
=> RHPAM-3897: switch to jboss-transaction-spi-jakarta

kie-soup-dataset/kie-soup-dataset-sql-tests/pom.xml
**JIRA**: [RHPAM-3897](https://issues.redhat.com/browse/RHPAM-3897)
**referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1775
* https://github.com/kiegroup/jbpm/pull/2028
* https://github.com/kiegroup/drools/pull/3839
* https://github.com/kiegroup/droolsjbpm-integration/pull/2609
* https://github.com/kiegroup/jbpm-work-items/pull/218
* https://github.com/kiegroup/kie-jpmml-integration/pull/67
* https://github.com/kiegroup/optaplanner/pull/1580
* https://github.com/jboss-integration/rhba-installers/pull/93
=> [7.59.x] RHPAM-3897: switch to jboss-transaction-spi-jakarta

kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/Aether.java
adding system properties to the artifact resolution.
=> [JBPM-10062] properties on custom settings are not available on kie server deploys

kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/AbstractFilesArtifactResolver.java, kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/ArtifactResolver.java, kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/ExplodedJarArtifactResolver.java, kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/InJarArtifactResolver.java
Jira: https://issues.redhat.com/browse/JBPM-9747
=> [JBPM-9747] Support springboot buildpack immutable images

kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/Aether.java
Jira: https://issues.redhat.com/browse/JBPM-10062
=> [7.67.x] [JBPM-10062] properties on custom settings are not available on kie server deploys

kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/Aether.java
Jira: https://issues.redhat.com/browse/JBPM-10062
=> [7.67.x-blue] [JBPM-10062] properties on custom settings are not available on kie server deploys

kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/AbstractFilesArtifactResolver.java, kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/ArtifactResolver.java, kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/ExplodedJarArtifactResolver.java, kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/InJarArtifactResolver.java
Jira: https://issues.redhat.com/browse/JBPM-9747
=> [7.67.x] [JBPM-9747] Support springboot buildpack immutable images

kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/AbstractFilesArtifactResolver.java, kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/ArtifactResolver.java, kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/ExplodedJarArtifactResolver.java, kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/InJarArtifactResolver.java
Jira: https://issues.redhat.com/browse/JBPM-9747
=> [7.67.x-blue] [JBPM-9747] Support springboot buildpack immutable images

pom.xml
Related PRs:
- https://github.com/kiegroup/kie-soup/pull/255
- https://github.com/kiegroup/kie-soup/pull/256
- https://github.com/kiegroup/kie-soup/pull/257
droolsjbpm-build-boostrap related PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2081
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2082
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2083
=> RHPAM-4525 lucene version property removed and inherited from parent

kie-soup-dataset/pom.xml, pom.xml
…ES module from build
https://issues.redhat.com/browse/BXMSPROD-1845
improving https://github.com/kiegroup/appformer/pull/1318
Referenced PRs:
* https://github.com/kiegroup/appformer/pull/1365
* https://github.com/kiegroup/kie-wb-common/pull/3792
=> BXMSPROD-1845: removed ElasticSearch dependency

kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/dialect/DB2Dialect.java, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/dialect/DefaultDialect.java, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/dialect/MySQLDialect.java, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/dialect/OracleDialect.java, kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/dialect/PostgresDialect.java
**Thank you for submitting this pull request**
**JIRA**:
[link](https://issues.redhat.com/browse/JBPM-10164)
=> [JBPM-10164] Adding millisecond date type support to dialects

kie-soup-maven-utils/kie-soup-maven-integration/pom.xml, kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/embedder/MavenProjectLoader.java, kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/embedder/WiredComponentProvider.java, kie-soup-maven-utils/kie-soup-maven-integration/src/test/java/org/appformer/maven/integration/embedder/MavenEmbedderTest.java
Replaces https://github.com/kiegroup/kie-soup/pull/275
=> [7.67.x-blue] RHPAM-3709: upgrade maven dependencies to address CVE-2021-26291
