- kie-soup-commons/pom.xml
- kie-soup-commons/src/main/java/org/kie/soup/commons/xstream/AnyAnnotationTypePermission.java
- kie-soup-commons/src/main/java/org/kie/soup/commons/xstream/LocalDateTimeXStreamConverter.java
- kie-soup-commons/src/main/java/org/kie/soup/commons/xstream/LocalDateXStreamConverter.java
- kie-soup-commons/src/main/java/org/kie/soup/commons/xstream/LocalTimeXStreamConverter.java
- kie-soup-commons/src/main/java/org/kie/soup/commons/xstream/OffsetDateTimeXStreamConverter.java
- kie-soup-commons/src/main/java/org/kie/soup/commons/xstream/XStreamUtils.java
This PR fixes a bad dependency from uberfire onto kie-internal (since droolsjbpm-knowledge is built after uberfire in the build system). This dependency was a temporary side-effect of migrating Guvnor modules to uberfire.
> AF-593+: Move XStreamUtils to kie-soup.

- kie-soup-commons/src/main/java/org/kie/soup/commons/util/ListSplitter.java
- kie-soup-commons/src/test/java/org/kie/soup/commons/util/ListSplitterTest.java
This is **cherry-pick** of #31 
@manstis @Rikkola please have a look.
> [7.5.x] DROOLS-2263: Cover case when not all enums use quote character

- kie-soup-dataset/kie-soup-dataset-elasticsearch/src/test/java/org/dashbuilder/dataprovider/backend/elasticsearch/suite/ElasticSearchTestSuite.java
- kie-soup-dataset/kie-soup-dataset-elasticsearch/src/test/resources/elasticsearch.yml
ElasticSearchTests failing if container already exists
https://issues.jboss.org/browse/AF-1145
> AF-1145 test fix as cherry pick

- kie-soup-commons/src/main/java/org/kie/soup/commons/util/ListSplitter.java
- kie-soup-commons/src/test/java/org/kie/soup/commons/util/ListSplitterTest.java
https://issues.jboss.org/browse/DROOLS-2629
(cherry picked from commit e2db1470676940ee99da79d35d932cde17371f93)
Fix is in two PRs:
https://github.com/kiegroup/kie-soup/pull/49
https://github.com/kiegroup/kie-wb-common/pull/1913
> [7.7.x] DROOLS-2629 : Complex enumerations are not selected in BRL multi value constraint (#47)

- kie-soup-bom/pom.xml
- pom.xml
jboss-ip-bom 8.1.0.Final is identical to 8.1.0.CR2 - we had to do this as prod will work only with Final versions. In future there won't be anymore CRs for jboss-ip-bom - only Final versions.
> upgraded jboss-ip-bom to 8.1.0.Final

- kie-soup-maven-utils/kie-soup-maven-integration/pom.xml
Fixes the warning
"[WARNING] Parameter tasks is deprecated, use target instead"
See maven-antrun-plugin [docs](http://maven.apache.org/plugins/maven-antrun-plugin/run-mojo.html#tasks)
> Use <target> instead of deprecated <tasks> in antrun plugin config

- kie-soup-commons/pom.xml
- kie-soup-commons/src/main/java/org/kie/soup/commons/util/Lists.java
- kie-soup-commons/src/test/java/org/kie/soup/commons/util/ListsTest.java
Hi @romartin, @manstis,
I added `addAll` method for Lists Builder to make it easier to minimize amount of generated classes.
> addAll method implemented for lists builder

- kie-soup-bom/pom.xml
- pom.xml
org.mvel is in jboss-ip-bom [8.3.3.Final](https://github.com/jboss-integration/jboss-integration-platform-bom/blob/8.3.3.Final/pom.xml#L326)
The version of mvel was here 2.3.2.Final. This was not aligned with mvel 2.4.3.Final - done yet.
> moved org.mvel to jboss-ip-bom 8.3.3.Final

- kie-soup-bom/pom.xml
- kie-soup-dataset/kie-soup-dataset-core/src/test/java/org/dashbuilder/dataset/DataSetDefRegistryTest.java
- kie-soup-dataset/kie-soup-dataset-sql-tests/pom.xml
- pom.xml
changed GAV since ...junit... is deprecated in the new mockito version
disabled maven-jar-plugin
upgraded missing versions to 7.24.0-SNAPSHOT
> BXMSPROD-8: refactor to build without jboss-ip-bom

- kie-soup-dataset/kie-soup-dataset-sql-tests/pom.xml
enabled the maven-jar-plugin again because the disabling of it causes much more problems then the problem:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.1.0:jar (default-jar) on project appformer-js: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them. -> [Help 1]
This error has to solved ASAP.
> revoked the disabling of maven-jar-plugin

- kie-soup-commons/pom.xml
- kie-soup-maven-utils/kie-soup-maven-support/pom.xml
- kie-soup-project-datamodel/kie-soup-project-datamodel-api/pom.xml
- kie-soup-project-datamodel/kie-soup-project-datamodel-commons/pom.xml
Module names properties are required by Maven bundle plugin to correctly set
bundle symbolic names.
> Add module names properties

- kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/def/SQLDataSetDef.java
- kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/impl/SQLDataSetDefBuilderImpl.java
- kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/JDBCUtils.java
- kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/SQLDataSetProvider.java
- kie-soup-dataset/kie-soup-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/SQLDataSetDefTest.java
backport targetting 7.4.1
https://issues.jboss.org/browse/RHPAM-2169
> JBPM-8559 - Avoid estimating query and table row counts and use prepared statement for reading columns metadata (#91)

- kie-soup-commons/src/main/java/org/kie/soup/commons/cron/CronExpression.java
- kie-soup-commons/src/main/resources/org/kie/soup/commons/KIESoupCommons.gwt.xml
- kie-soup-commons/src/test/java/org/kie/soup/commons/cron/CronExpressionTest.java
- Splits the CronExpression in drools into a GWT compatible part required by Stunner and the non GWT complatible methods remains in drools
(cherry picked from commit 9e6d8a6f41e29ce28da10a81b1643486b9bead37)
> [7.23.x] JBPM-8445: Stunner -  unable to set cycle timer with cron expression

- pom.xml
https://issues.jboss.org/browse/BXMSPROD-507
Parent PR kiegroup/droolsjbpm-build-bootstrap/pull/1095
Dependent:
* this #117
* kiegroup/appformer/pull/831
> BXMSPROD-507: removed netty version property

- pom.xml
related issue where duplicated version property causes the usage of old mvel2
I additionaly removed netty version property which is now in KIE-PARENT too
https://issues.jboss.org/browse/RHPAM-2517
> RHPAM-2517: removed duplicated version properties

- kie-soup-xstream/pom.xml
- kie-soup-xstream/src/main/java/org/kie/soup/xstream/AnyAnnotationTypePermission.java
- kie-soup-xstream/src/main/java/org/kie/soup/xstream/LocalDateTimeXStreamConverter.java
- kie-soup-xstream/src/main/java/org/kie/soup/xstream/LocalDateXStreamConverter.java
- kie-soup-xstream/src/main/java/org/kie/soup/xstream/LocalTimeXStreamConverter.java
- kie-soup-xstream/src/main/java/org/kie/soup/xstream/OffsetDateTimeXStreamConverter.java
- kie-soup-xstream/src/main/java/org/kie/soup/xstream/XStreamUtils.java
- pom.xml
a suite of PRs:
[kie-soup] this one
[droolsjbpm-build-bootstrap] https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1286
[appformer] https://github.com/kiegroup/appformer/pull/953
[drools] https://github.com/kiegroup/drools/pull/2874
[jbpm] https://github.com/kiegroup/jbpm/pull/1640
[droolsjbpm-integration] https://github.com/kiegroup/droolsjbpm-integration/pull/2078
[kie-wb-common] https://github.com/kiegroup/kie-wb-common/pull/3288
[drools-wb] https://github.com/kiegroup/drools-wb/pull/1356
[optaplanner-wb] https://github.com/kiegroup/optaplanner-wb/pull/367
[jbpm-wb] https://github.com/kiegroup/jbpm-wb/pull/1430
[kie-wb-playground] https://github.com/kiegroup/kie-wb-playground/pull/86
[droolsjbpm-tools] https://github.com/kiegroup/droolsjbpm-tools/pull/104
1. ALL and each of …
> KOGITO-1546 XStreamUtils kie-soup refactoring

- kie-soup-dataset/kie-soup-dataset-sql-tests/pom.xml
this was showing in maven build 
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.kie.soup:kie-soup-dataset-sql-tests:jar:7.39.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-surefire-plugin @ line 183, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```
> merged duplicated maven-surefire-plugin configuration

- kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/InJarArtifactResolver.java
There is no need to resolve artifacts anymore when building kie module. There should be already package.
https://issues.redhat.com/browse/JBPM-9344
> [JBPM-9344] Maven project loader requires solving pom with immutable spring boot images.

- kie-soup-security-utils/pom.xml
- kie-soup-security-utils/src/main/java/org/kie/soup/security/utils/BasicAuthorizationPrincipal.java
- pom.xml
https://issues.redhat.com/browse/DROOLS-5783
Description:
The goal of this PR is to cleanup `droolsjbpm-integration` repo from unnecessary relation with other repos (in this case `appformer`). It is a sort of followup of this PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1505 that tries to do the same but it has been partially reverted because of some remaining usages
Details of this part of the PR:
- adding `kie-soup-security-utils` to share `BasicAuthorizationPrincipal` impl
@mareknovotny @Ginxo @lucamolteni @mariofusco 
**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1517
* https://github.com/kiegroup/kie-soup/pull/163
* …
> [DROOLS-5783] Make droolsjbpm-integration repo independent from appformer

- kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/SQLDataSetProvider.java
Setting limits to 0 will only parse query to retrieve metadata, which
is what we precissely want.
https://issues.redhat.com/browse/JBPM-9099
> [JBPM-9099] Long running query at kie-server startup

- kie-soup-xstream/src/main/java/org/kie/soup/xstream/XStreamUtils.java
Adding new Xtream factory method that accepts mapper function
Merge with https://github.com/kiegroup/droolsjbpm-integration/pull/2369
> [JBPM-9558]  KIE using XStream does not complain on unknown fields

- kie-soup-project-datamodel/kie-soup-project-datamodel-api/src/main/java/org/kie/soup/project/datamodel/oracle/OperatorsOracle.java
- kie-soup-project-datamodel/kie-soup-project-datamodel-api/src/test/java/org/kie/soup/project/datamodel/OperatorsOracleTest.java
Guided decision table and guided rule editor will ofer 'contains' operator also for string fields
For more details see https://issues.redhat.com/browse/DROOLS-5883
Ensemble together with:
- https://github.com/kiegroup/drools/pull/3281
- https://github.com/kiegroup/drools-wb/pull/1448
> DROOLS-5883: Allow contains operator for string fields

- kie-soup-dataset/kie-soup-dataset-sql/src/main/java/org/dashbuilder/dataprovider/sql/dialect/DefaultDialect.java
Code now does not longer assume that a Date instance is received, but
also contemplates LocalDateTime, Number and String cases for
completeness
> [JBPM-9592] External DB driver not working-MySQL

- kie-soup-project-datamodel/kie-soup-project-datamodel-api/src/main/java/org/kie/soup/project/datamodel/oracle/DataType.java
- kie-soup-project-datamodel/kie-soup-project-datamodel-api/src/test/java/org/kie/soup/project/datamodel/oracle/DataTypeTest.java
(cherry picked from commit a26296b9b2d37e9ba4979afad2619c8f88509923)
**JIRA**: [DROOLS-6033](https://issues.redhat.com/browse/DROOLS-6033)
**Referenced Pull Requests**:
* https://github.com/kiegroup/kie-soup/pull/185
* https://github.com/kiegroup/kie-wb-common/pull/3585
<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>
* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>
> [7.48.x] DROOLS-6033 : LocaldateTime guided rule presents it incorrectly.

- kie-soup-dataset/kie-soup-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/SQLDataSetMetadataLimitTest.java
**[JBPM-9646](https://issues.redhat.com/browse/JBPM-9646)**: Task inbox fails to display data due to inefficient jbpmHumanTasksWithUser query
> [JBPM-9646] - Test case for JBPM-9619 - Task inbox fails to display data due to inefficient jbpmHumanTasksWithUser query

- kie-soup-dataset/kie-soup-dataset-kafka/src/main/java/org/dashbuilder/dataprovider/kafka/mbean/JMXRMIConnectorProvider.java
- kie-soup-dataset/kie-soup-dataset-kafka/src/main/java/org/dashbuilder/dataprovider/kafka/mbean/MBeanServerConnectionProvider.java
**JIRA**: https://issues.redhat.com/browse/JBPM-9678
Part of an Ensemble, merge with:
https://github.com/kiegroup/kie-wb-distributions/pull/1092
https://github.com/kiegroup/appformer/pull/1122
How to test:
* Using Business Central create a Kafka data set. See this PR for more information: https://github.com/kiegroup/appformer/pull/1104
* Try the same with thorntail distribution
Description:
For Kafka Data Set providers we have to open RMI connections. With pure Java that's not the problem because all JVM have a default RMI connector provider that can be used for MBeans remote invocation. 
However, in EAP JBoss will try to set its own provider, see the module "org.jboss.remoting-jmx" the code is in [1]. All would be great but the module that contains the JMX connector is not a module added …
> JBPM-9678: Standalone workbench does not start

- kie-soup-xstream/src/main/java/org/kie/soup/xstream/XStreamUtils.java
(cherry picked from commit 8cb469dac9b9c0c3a47cf7a329dfefd55d5ed22d)
> [DROOLS-6270] always use secure xstream marshaller in drools (#191)

- .github/workflows/pull_request.yml
See build-chain update details at https://github.com/kiegroup/github-action-build-chain/pull/190
related PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1798
- https://github.com/kiegroup/kie-soup/pull/235
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/576
- https://github.com/kiegroup/drools/pull/3959
- https://github.com/kiegroup/optaplanner/pull/1640
- https://github.com/kiegroup/lienzo-core/pull/156
- https://github.com/kiegroup/lienzo-tests/pull/130
- https://github.com/kiegroup/appformer/pull/1208
- https://github.com/kiegroup/kie-uberfire-extensions/pull/127
- https://github.com/kiegroup/jbpm/pull/2053
- https://github.com/kiegroup/kie-jpmml-integration/pull/69
- https://github.com/kiegroup/droolsjbpm-integration/pull/2638
- …
> [ISSUE 117] build-chain upgraded to v2.6.13

- kie-soup-dataset/kie-soup-dataset-elasticsearch/pom.xml
KOGITO-6404: Remove unused loggers in Dashbuilder
Backport
Merge with https://github.com/kiegroup/appformer/pull/1219
> KOGITO-6404: Remove unused loggers in Dashbuilder

- pom.xml
Related PRs:
- https://github.com/kiegroup/kie-soup/pull/255
- https://github.com/kiegroup/kie-soup/pull/256
- https://github.com/kiegroup/kie-soup/pull/257
droolsjbpm-build-boostrap related PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2081
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2082
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2083
> [7.67.x] RHPAM-4525 lucene version property removed and inherited from parent

- pom.xml
Related PRs:
- https://github.com/kiegroup/kie-soup/pull/255
- https://github.com/kiegroup/kie-soup/pull/256
- https://github.com/kiegroup/kie-soup/pull/257
droolsjbpm-build-boostrap related PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2081
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2082
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2083
> [7.67.x-blue] RHPAM-4525 lucene version property removed and inherited from parent

- kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/AbstractFilesArtifactResolver.java
- kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/ExplodedJarArtifactResolver.java
- kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/InJarArtifactResolver.java
- kie-soup-maven-utils/kie-soup-maven-integration/src/test/java/org/appformer/maven/integration/ArtifactResolverTest.java
- kie-soup-maven-utils/kie-soup-maven-integration/src/test/resources/BOOT-INF/classes/KIE-INF/lib/kjar-1.0.0-20240717-143315-1.pom
- kie-soup-maven-utils/kie-soup-maven-integration/src/test/resources/BOOT-INF/classes/KIE-INF/lib/kjar-1.0.0-SNAPSHOT.pom
Ignore timestamped SNAPSHOT replacements to find and parse pom artifact
**JIRA**: https://issues.redhat.com/browse/RHPAM-4970
> RHPAM-4970 locate pom with snapshot versioning on Springboot
